# Generated by Django 3.2.9 on 2021-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trashcans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('kinds', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=20)),
                ('web_link', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
