# Generated by Django 3.2.9 on 2021-12-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trashcans',
            new_name='Restaurants',
        ),
    ]
