# Generated by Django 3.2.9 on 2021-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_restaurants_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='score',
            field=models.FloatField(),
        ),
    ]
